// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/21/2026, 5:00:37 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/tr3p0l3m/Projects/ceeveegen/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/tr3p0l3m/Projects/ceeveegen/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/tr3p0l3m/Projects/ceeveegen/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/tr3p0l3m/Projects/ceeveegen/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/tr3p0l3m/Projects/ceeveegen/plugins/**/*.{js,ts,mjs}","/home/tr3p0l3m/Projects/ceeveegen/composables/**/*.{js,ts,mjs}","/home/tr3p0l3m/Projects/ceeveegen/utils/**/*.{js,ts,mjs}","/home/tr3p0l3m/Projects/ceeveegen/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/tr3p0l3m/Projects/ceeveegen/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/tr3p0l3m/Projects/ceeveegen/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/tr3p0l3m/Projects/ceeveegen/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;